### ISSUE TITLE
Fix commit signing

### ISSUE THREAD

**Issue by colincasey** [heroku/languages-github-actions#132]
The commit signing configuration shown below doesn't work as expected with [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request):

```yaml
- name: Configure git
  run: |
    git config --global user.name ${{ inputs.app_username }}
    git config --global user.email ${{ inputs.app_email }}
```

Instead, this should be configured using the `committer` and `author` inputs on the [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) action. E.g.;

```
- name: Create Pull Request
  id: pr
  uses: peter-evans/create-pull-request@v5
  with:
    committer: ${{ inputs.app_username }} <${{ inputs.app_email }}>
    author: ${{ inputs.app_username }} <${{ inputs.app_email }}>
    # ...
```

GUS-W-14041925.
